columnSuffix: null
contentColumnType: string
fieldGroup: e3675fcb-bfe6-4b0f-bad2-80f8c81f46c3 # Common
handle: articlePhoto
instructions: ''
name: 'Article Photo'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:d97b0887-4ef6-4dac-a400-4147cf63020c' # Image
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:d97b0887-4ef6-4dac-a400-4147cf63020c' # Image
  singleUploadLocationSubpath: article
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
