defaultPlacement: end
enableVersioning: false
handle: people
name: People
propagationMethod: all
siteSettings:
  9423f990-30c3-4b68-8ef4-c6e496778e9a: # Tribes Test
    enabledByDefault: true
    hasUrls: true
    template: people/_entry
    uriFormat: 'people/{slug}'
type: channel
